### ISSUE TITLE
Erros in CannyThreshold and trackFiltredObject

### ISSUE THREAD

**Issue by chfakht** [akaifi/MultiObjectTrackingBasedOnColor#1]
Hi , i'm using opencv 3.0.0 and visual studio 2013 pro
when i build my project i get the following errors 

CannyThreshold : undefined identifier
trackFiltredObject : function does not take 3 arguments

**Comment by akaifi** [comment]
Dear @chfakht,

you can just delete or comment those, and it should work!  

Feel free to send a poll request if you git it to work

Thanks,

**Comment by akaifi** [comment]
I update the code to fix this issue
